[koreader]
source = "github"
github = "koreader/koreader"
prefix = "v"
use_latest_release = true
[koreader-noto-sans-arabic-ui]
source = "git"
git = "https://salsa.debian.org/fonts-team/fonts-noto.git"
prefix = "debian/"
include_regex = 'debian/.*'
